# Generated by Django 2.0.2 on 2018-02-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='姓名')),
                ('sex', models.CharField(max_length=100, verbose_name='性别')),
                ('email', models.CharField(max_length=100, verbose_name='姓名')),
            ],
        ),
    ]
