# Generated by Django 2.0.2 on 2018-02-04 15:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('webinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 2, 4, 15, 30, 56, 42753, tzinfo=utc), verbose_name='注册时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='update_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更新时间'),
        ),
    ]
