# Generated by Django 2.0.2 on 2018-02-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webinfo', '0002_auto_20180204_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=100, verbose_name='邮箱'),
        ),
    ]
