# Generated by Django 2.0.2 on 2018-02-04 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinfo', '0003_auto_20180204_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='update_time',
        ),
    ]
